### ISSUE TITLE
Bad method JHtml::_('bootstrap.framework');

### ISSUE THREAD

**Issue by 2FR3** [kevinsguides/j4starter#1]
Hi and thx for your free work.
Please visit https://gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd

Else we have lot of script called :
`<script src="[/xxx/media/vendor/bootstrap/js/alert.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/alert.min.js?5.2.3)" type="module"></script>
	<script src="[/xxxi/media/vendor/bootstrap/js/button.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/button.min.js?5.2.3)" type="module"></script>
	<script src="[/xxxi/media/vendor/bootstrap/js/carousel.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/carousel.min.js?5.2.3)" type="module"></script>
	<script src="[/xxx/media/vendor/bootstrap/js/collapse.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/collapse.min.js?5.2.3)" type="module"></script>
	<script src="[/xxx/media/vendor/bootstrap/js/dropdown.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/dropdown.min.js?5.2.3)" type="module"></script>
	<script src="[/xxxi/media/vendor/bootstrap/js/modal.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/modal.min.js?5.2.3)" type="module"></script>
	<script src="[/xxx/media/vendor/bootstrap/js/offcanvas.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/offcanvas.min.js?5.2.3)" type="module"></script>
	<script src="[/xxx/media/vendor/bootstrap/js/popover.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/popover.min.js?5.2.3)" type="module"></script>
	<script src="[/xxx/media/vendor/bootstrap/js/scrollspy.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/scrollspy.min.js?5.2.3)" type="module"></script>
	<script src="[/xxx/media/vendor/bootstrap/js/tab.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/tab.min.js?5.2.3)" type="module"></script>
	<script src="[/xxx/media/vendor/bootstrap/js/toast.min.js?5.2.3](view-source:http://localhost/paxdei/media/vendor/bootstrap/js/toast.min.js?5.2.3)" type="module"></script>`

And we need JQuery ?

Sorry for my poor english, and it's my first time with Joomla...

**Comment by kevinsguides** [comment]
Thanks for bringing this up, yes I should probably get rid of that call.

Regards
Kevin
