### ISSUE TITLE
Not installable and menu problems

### ISSUE THREAD

**Issue by radik10** [kevinsguides/j4starter#2]
Hi, thanks for this template.

But there are some issues:
1. when you download template from github, ZIP is not installable - missing XML file for installation of folders/files, you need to install it manually, folder by folder and then discover the template in joomla 4 
2. when you resize browser, there are 2 hamburger buttons, should be only one,
3. main menu has as many rows as menu has items. This is bug since long time ago. How to have correct menu (1 row with its menu items)?

Thank you
Radovan

![JoomStarter-main - BUGS](https://github.com/user-attachments/assets/c6197611-dd5c-44e8-96bb-db97e94d2004)

**Comment by kevinsguides** [comment]
You need to make sure you're installing from the zip under the releases page. 
https://github.com/kevinsguides/JoomStarter/releases

You don't install by downloading the git repo as a zip. The repo is structured for development, the releases are structured for installation and should work as usual by uploading the zip through extension installer.
I will look into the other issues.
Thanks - Kevin

**Comment by kevinsguides** [comment]
For the menu to appear correctly you need to make sure you're using the default module layout in the menu module and not cassiopeia's layout.
![image](https://github.com/user-attachments/assets/1c2891c7-1fcc-4540-9438-6bd45bfe67ae)

**Comment by kevinsguides** [comment]
I've added that note on the menu module layout to the documentation. Hopefully that resolves all your issues. Let me know if you have any other problems. Thanks.
